"""upd users

Revision ID: 7a6440d23f1d
Revises: 4a027e692712
Create Date: 2023-11-25 17:36:32.199912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6440d23f1d'
down_revision = '4a027e692712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Created datetime'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update datetime'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users__id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__users__id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
