"""upd

Revision ID: 4a027e692712
Revises: 0f5ae4addbd2
Create Date: 2023-11-21 23:06:00.549598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a027e692712'
down_revision = '0f5ae4addbd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_computer', sa.Column('disc_id', sa.BigInteger(), nullable=False))
    op.add_column('virtual_computer', sa.Column('connections', sa.Boolean(), nullable=True))
    op.alter_column('virtual_computer', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Created datetime',
               existing_server_default=sa.text('now()'))
    op.alter_column('virtual_computer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Last update datetime',
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq__virtual_computer__disk_id', 'virtual_computer', type_='unique')
    op.create_index(op.f('ix__virtual_computer__disc_id'), 'virtual_computer', ['disc_id'], unique=True)
    op.create_index(op.f('ix__virtual_computer__id'), 'virtual_computer', ['id'], unique=True)
    op.drop_column('virtual_computer', 'disk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_computer', sa.Column('disk_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix__virtual_computer__id'), table_name='virtual_computer')
    op.drop_index(op.f('ix__virtual_computer__disc_id'), table_name='virtual_computer')
    op.create_unique_constraint('uq__virtual_computer__disk_id', 'virtual_computer', ['disk_id'])
    op.alter_column('virtual_computer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Last update datetime',
               existing_server_default=sa.text('now()'))
    op.alter_column('virtual_computer', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Created datetime',
               existing_server_default=sa.text('now()'))
    op.drop_column('virtual_computer', 'connections')
    op.drop_column('virtual_computer', 'disc_id')
    # ### end Alembic commands ###
