"""init

Revision ID: ffe54ee623e9
Revises: 
Create Date: 2023-12-04 19:38:36.572914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe54ee623e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_computer',
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('disc', sa.Integer(), nullable=False),
    sa.Column('disc_id', sa.String(), nullable=False),
    sa.Column('connections', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Created datetime'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update datetime'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__virtual_computer'))
    )
    op.create_index(op.f('ix__virtual_computer__disc_id'), 'virtual_computer', ['disc_id'], unique=True)
    op.create_index(op.f('ix__virtual_computer__id'), 'virtual_computer', ['id'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Created datetime'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update datetime'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users__id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__users__id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix__virtual_computer__id'), table_name='virtual_computer')
    op.drop_index(op.f('ix__virtual_computer__disc_id'), table_name='virtual_computer')
    op.drop_table('virtual_computer')
    # ### end Alembic commands ###
